### ISSUE TITLE
Livekit URL path suffix

### ISSUE THREAD

**Issue by joaogbcravo** [livekit/rust-sdks#217]
I'm using livekit behind a reverse proxy, and have the traffic being routed to livekit using a suffix path.

Let's say `wss://localhost/my/custom/path`. I can make Javascript clients use this path, and even the livekit Meet doesn't complain. 
However, it seems that Rust SDK (and the SDKs that use it, like python) just ignores `my/custom/path` and replace it completely with just `/rtc`

The root cause seems to be in the [line](https://github.com/livekit/rust-sdks/blob/327472c8fc4d5d66c97a9cc20b7f48d754bb2d01/livekit-api/src/signal_client/mod.rs#L302C4-L302C29). 

Can this be changed?

**Comment by theomonnom** [comment]
Yes, it seems like the behaviour of the client-sdk-js is to append `rtc/`
We're currently overriding the path on the Rust SDK, I can push a fix
