### ISSUE TITLE
Missing support for topic in data transfer protocol

### ISSUE THREAD

**Issue by trzeciak** [livekit/rust-sdks#248]
Is any short-term plan, to support 'topic' in data transfer, or not?

For example in swiftSDK, I can send data+topic to participant(s): 
https://github.com/livekit/client-sdk-swift/blob/08229eb195e17743d10f08534a4d39e9b2bd1905/Sources/LiveKit/Participant/LocalParticipant.swift#L261-L275

and receive data+topic as delegate:
https://github.com/livekit/client-sdk-swift/blob/08229eb195e17743d10f08534a4d39e9b2bd1905/Sources/LiveKit/Protocols/RoomDelegate.swift#L119-L122

In rust-sdks you can find the "topic" string, but it is very weak:
https://github.com/search?q=repo%3Alivekit%2Frust-sdks%20topic&type=code

**Comment by theomonnom** [comment]
Fixed by https://github.com/livekit/rust-sdks/pull/256
