### ISSUE TITLE
Mingw windows support

### ISSUE THREAD

**Issue by Rajiv91** [livekit/rust-sdks#317]
Hey
I'm working on windows, i have a go project where i want to call the rust sdk bindings of this repo, however cgo can't work with the msvc compiler, from your notes i see that currently is only available with msvc. Will you add support for mingw soon or how difficult would it be to try to compile it using the mingw toolchain?

**Comment by dennwc** [comment]
Did you try [server-sdk-go](https://github.com/livekit/server-sdk-go)? Is it missing some functionality that you want to use?

**Comment by Rajiv91** [comment]
Hey
Yeah, it's missing all the encoding stuff with libwebrtc libraries in the go sdk
