### ISSUE TITLE
internal error: "failed to send data packet Send" , when offen use rust-sdks to publishData  

### ISSUE THREAD

**Issue by wangtianyang0** [livekit/rust-sdks#335]
Dear developer,
      When I used the rust-sdks to build the lib liblivekit_ffi.so for the c-plusplus code,and use the lib to publishdata message to the livekit-server.And when I send the message more offen,such as no sleep in the loop , when the async_id reached over 170000 or more ,there will be a engine: **internal error occured** ,and the error is "**failed to send data packet Send**". The connect to the server is OK, and the client can`t publishData to the livekit-Server again any more.
     Is there any size limited to publishData to the livekit-server at a single time,or if there is something wrong with my rust-sdks, could you give me some advice? 
                                                                                                                                                                          
The rust-sdks version is [ffi-v0.4.1]
The livekit-server version is latest.
                                                                                                                                         Sincerely,
                                                                                                                                               Your rust-sdks user.
                                                                                                                                                Best wishes to you.

**Comment by theomonnom** [comment]
Hey, are you correctly waiting for the PublishDataCallback?

**Comment by wangtianyang0** [comment]
Yes, I do the waiting correctly,and just when the async_id reached over 170000 or more ,there will be a engine: internal error occured ,and the error is "failed to send data packet Send".
