### ISSUE TITLE
Would this work on an embedded/IOT setup?

### ISSUE THREAD

**Issue by talksik** [livekit/rust-sdks#366]
Hello there, I am considering using livekit for a set up where we want to send audio back and forth from two separate devices.

I am concerned that perhaps I will run into issues here depending on the underpinnings of this sdk. Is the Linux support merely for desktop x64 machines or will it also work on embedded ARM devices like say the raspberrypi. I have a knowledge gap so just wanted to fish for help before I get my hands dirty.

Would you instead recommend that I implement a simple UDP relay server and use gstreamer on client devices instead of this SDK?

**Comment by davidzhao** [comment]
It should work well for embedded devices. The Rust SDK should build fine for ARM architectures. Audio encoding is fairly light weight and shouldn't be an issue at all.

**Comment by talksik** [comment]
Thanks @davidzhao !  Appreciate the note on the pre-built binaries
